name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "ZEBO1XP"
          ICON_FIRST: "#007b5c"
          ICON_SECOND: "#00bf8f"
          BACKGROUND_FIRST: "#004736"
          BACKGROUND_SECOND: "#00bf8f"
          LANG: "en"
          # CARD_WIDTH: "400"
          # UPDATE_TIME: "true"
